version: "3"
services:

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: password
  
  redis:
    image: redis:alpine

  misp:
    image: 0xiso/misp
    ports:
      - "8080:80" # MISP Web interface
      - "50000:50000" # MISP ZMQ
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # MISP_BASEURL : http://127.0.0.1/
      MISP_MODULES_HOST: misp-modules
      MISP_LIVE: 1
      MISP_DISABLE_EMAILING: 1
      MISP_ENRICHMENT_ENABLE: 1
      MISP_IMPORT_ENABLE: 1
      MISP_EXPORT_ENABLE: 1
      MISP_ZEROMQ_ENABLE: 1

  misp-modules:
    image: 0xiso/misp-modules
