version: "3"
services:

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: password
  
  redis:
    image: redis:alpine

  misp:
    build: .
    image: 0xiso/misp
    ports:
      - "8080:80" # MISP Web interface
      - "50000:50000" # MISP ZMQ
    volumes:
      - ./misp-attachments:/misp-attachments
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MISP_BASEURL : ""
      MISP_MODULES_HOST: misp-modules
      MISP_LIVE: 1
      MISP_DISABLE_EMAILING: 1
      MISP_ENRICHMENT_ENABLE: 1
      MISP_IMPORT_ENABLE: 1
      MISP_EXPORT_ENABLE: 1
      MISP_ZEROMQ_ENABLE: 1
      MISP_ATTACHMENTS_DIR: /misp-attachments
      MISP_SCHEDULER_WORKER_ENABLE: 1
      MISP_FIX_PERMISSION: 1

  misp-modules:
    build: ./misp-modules/
    image: 0xiso/misp-modules

  # redis-commander:
  #   image: rediscommander/redis-commander
  #   restart: always
  #   environment:
  #   - REDIS_HOSTS=local:redis:6379
  #   ports:
  #   - "8081:8081"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #   restart: always
  #   ports:
  #    - 8082:80
